### PR TITLE
Don't monkey patch HTML's list of activation triggering input event

### PR DESCRIPTION
**Pull request by marcoscaceres**
Related fix on the HTML side:
https://github.com/whatwg/html/pull/6818

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/pointerlock/pull/70.html" title="Last updated on Aug 13, 2021, 6:21 AM UTC (1a354a7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pointerlock/70/b47d8dd...1a354a7.html" title="Last updated on Aug 13, 2021, 6:21 AM UTC (1a354a7)">Diff</a>

### CODE REVIEW

**Review by mustaqahmed — APPROVED** [review]
We can land this now without waiting for the HTML change (because HTML needs to address https://github.com/whatwg/html/issues/3849 anyway).

**Comment by marcoscaceres** [comment]
@mustaqahmed, looks like "activation triggering input event" vanished from HTML. Any idea what that should be now?

**Comment by mustaqahmed** [comment]
> @mustaqahmed, looks like "activation triggering input event" vanished from HTML. Any idea what that should be now?

Sorry trying to understand what you meant by "vanished"...I can still see it [here](https://html.spec.whatwg.org/multipage/interaction.html#activation-triggering-input-event).  Perhaps you meant a missing `<dfn export>` instead, which is being added in https://github.com/whatwg/html/pull/6818?

**Review by mustaqahmed — APPROVED** [review]

**Comment by marcoscaceres** [comment]
Ah, indeed! I thought it was exported already! Sorry for the confusion on my part.

**Comment by mustaqahmed** [comment]
@marcoscaceres I got a chance to look at it again after a while, and now it seems to me we can significantly clarify the current dependence to HTML if we simply drop the "engagement gesture" section and fix the existing 5 references by:
1. saying `requestPointerLock()` is a [Transient activation-gated API](https://html.spec.whatwg.org/multipage/interaction.html#transient-activation-gated-api), and
2. adding the non-normative exception currently mentioned in the "Note" about "no engagement gesture is required".

This change would make the text more precise, and as a bonus point, we will be able to land this PR independently from whatwg/html#6818.

What do you think?

**Comment by marcoscaceres** [comment]
sounds great, @mustaqahmed. The only thing would be getting "activation triggering input event" exported from HTML, but what you suggest makes sense.

**Comment by mustaqahmed** [comment]
Please consider the [suggestion above](https://github.com/w3c/pointerlock/pull/70#issuecomment-912772669) without getting blocked by a holistic (and possibly involved) change needed on the HTML side.  Landing the PointerLock change here before the HTML change would still be a big improvement because the current "engagement gesture" section is too incomplete anyway (it doesn't mention PointerEvents or TouchEvents, for example).

**Pull request closed without merging**
