### PR TITLE
Change movementX/Y type to double 

### LINKED ISSUE #24: movementX/Y to be double instead of long
Following [the extension](https://drafts.csswg.org/cssom-view/#extensions-to-the-mouseevent-interface) that changes screenX/Y type to double I'd suggest we also change the type of movementX/Y to double. @scheib do you imagine any scenario that this might break stuff for any developers?

### PR DESCRIPTION
**Pull request by EiraGe**
Closes #24

***
<a href="https://pr-preview.s3.amazonaws.com/EiraGe/pointerlock/pull/68.html" title="Last updated on Jun 14, 2021, 4:05 PM UTC (6a84b57)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/pointerlock/68/b043c1b...EiraGe:6a84b57.html" title="Last updated on Jun 14, 2021, 4:05 PM UTC (6a84b57)">Diff</a>

### CODE REVIEW

**Comment by EiraGe** [comment]
Hi @mustaqahmed PTAL Thanks

**Review by mustaqahmed — APPROVED** [review]
Thanks, LGTM.  Sorry for missing the original PR for so long.

**Comment by mustaqahmed** [comment]
@marcoscaceres I am about to merge this PR ignoring the Travis failures (caused by existing references to external specs).  Just wanted to double-check with you if this is okay.

**Comment by marcoscaceres** [comment]
@mustaqahmed, checking what's going on.

**Comment by marcoscaceres** [comment]
Sent #69 ... @mustaqahmed, if you'd like to merge this on, that's ok. Alternatively, let's fix #69 and rebase this.

**Pull request merged**
