### PR TITLE
Add Mustaq as editor

### PR DESCRIPTION
**Pull request by NavidZ**
@LJWatson, could you add @mustaqahmed to the WebAppsWG as well.

***

### :boom: Error: 500 Internal Server Error :boom: ###

[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on May 29, 2020, 4:28 PM UTC)_.

<details>
<summary>More</summary>

PR Preview relies on a number of web services to run. There seems to be an issue with the following one:

:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.

:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Frawcdn.githack.com%2Fw3c%2Fpointerlock%2Feeb8e227f65c9e84c7883f656b3e0494a9cadf46%2Findex.html%3FisPreview%3Dtrue)

```
[33m📡 HTTP Error 522:[39m [36mhttps://rawcdn.githack.com/w3c/pointerlock/eeb8e227f65c9e84c7883f656b3e0494a9cadf46/index.html[39m
```

_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20w3c/pointerlock%2363.)._
</details>

### CODE REVIEW

**Comment by LJWatson** [comment]
@mustaqahmed will need to ask Google's AC rep @cwilso to add them to the WebApps WG.

I didn't see a request to add @mustaqahmed as an editor come through to the WebApps chairs. @marcoscaceres?

**Comment by NavidZ** [comment]
> @mustaqahmed will need to ask Google's AC rep @cwilso to add them to the WebApps WG.
> 
> I didn't see a request to add @mustaqahmed as an editor come through to the WebApps chairs. @marcoscaceres?

Sure. I'll followup with Chris.

**Review by marcoscaceres — APPROVED** [review]

**Comment by NavidZ** [comment]
@marcoscaceres any reason this is failing Travis bot? I don't see any connection between the PR and the error shown in there.

**Comment by marcoscaceres** [comment]
It's failing because it's trying to link to "triggered by user activation", which is no longer a thing... we need to fix that first before we merge this... And @mustaqahmed is exactly the person we need to fix that in the spec 😊

@mustaqahmed, could you send a separate PR for to use the new activation model? Then we can update this so it doesn't fail.

**Comment by mustaqahmed** [comment]
I created this PR for the new activation model #65, ptal.

**Comment by marcoscaceres** [comment]
Thanks @mustaqahmed - sorry for the additional setup, but I need you to link your W3C account with your GitHub account: https://www.w3.org/users/myprofile/connectedaccounts - that should be the last thing we need, assuming you've joined the working group already. In case you haven't already, there is a join link at the bottom right of https://www.w3.org/2019/webapps/

**Pull request merged**
